import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export interface ConfigEnvInput {
  workDir: string;
  resultRoot: string;
  tmpDir: string;
  slcData: string;
  demFinal: string;
  enviIdl: string;
  sarscapeLib: string;
  gacosList: string;
  sarModules: string;
  slcRoi?: string;
  slcPolarization?: string;
  demRaw?: string;
  demDat?: string;
  demEnvi?: string;
}

/** 生成 config.env 文本（字段名与 experiment/bat 读取的一致）。 */
export function buildConfigEnv(input: ConfigEnvInput): string {
  const lines = [
    "# ===== auto-generated by insar_pipeline (do not hand-edit) =====",
    `WORK_DIR=${input.workDir}`,
    `RESULT_ROOT=${input.resultRoot}`,
    `TMP_DIR=${input.tmpDir}`,
    `SLC_DATA=${input.slcData}`,
    `SLC_ROI=${input.slcRoi ?? ""}`,
    `SLC_POLARIZATION=${input.slcPolarization ?? "ONLY_VV_POL"}`,
    `DEM_RAW=${input.demRaw ?? ""}`,
    `DEM_DAT=${input.demDat ?? ""}`,
    `DEM_ENVI=${input.demEnvi ?? ""}`,
    `DEM_FINAL=${input.demFinal}`,
    `DEM_FILE=${input.demFinal}`,
    `GACOS_LIST=${input.gacosList}`,
    `SAR_MODULES=${input.sarModules}`,
    `ENVI_IDL=${input.enviIdl}`,
    `SARSCAPE_LIB=${input.sarscapeLib}`,
  ];
  return lines.join("\n") + "\n";
}

/** 写 config.env 到实验目录（resultRoot 根下）。 */
export function writeConfigEnv(resultRoot: string, input: ConfigEnvInput): string {
  const envPath = join(resultRoot, "config.env");
  mkdirSync(resultRoot, { recursive: true });
  writeFileSync(envPath, buildConfigEnv(input), "utf8");
  return envPath;
}
