import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
/** 生成 config.env 文本（字段名与 experiment/bat 读取的一致）。 */
export function buildConfigEnv(input) {
    const lines = [
        "# ===== auto-generated by insar_pipeline (do not hand-edit) =====",
        `WORK_DIR=${input.workDir}`,
        `RESULT_ROOT=${input.resultRoot}`,
        `TMP_DIR=${input.tmpDir}`,
        `SLC_DATA=${input.slcData}`,
        `SLC_ROI=${input.slcRoi ?? ""}`,
        `SLC_POLARIZATION=${input.slcPolarization ?? "ONLY_VV_POL"}`,
        `DEM_RAW=${input.demRaw ?? ""}`,
        `DEM_DAT=${input.demDat ?? ""}`,
        `DEM_ENVI=${input.demEnvi ?? ""}`,
        `DEM_FINAL=${input.demFinal}`,
        `DEM_FILE=${input.demFinal}`,
        `GACOS_LIST=${input.gacosList}`,
        `SAR_MODULES=${input.sarModules}`,
        `MAX_PERC_BASELINE=${input.maxPercBaseline ?? 2}`,
        `MAX_TIME_BASELINE=${input.maxTimeBaselineDays ?? 180}`,
        `ENVI_IDL=${input.enviIdl}`,
        `SARSCAPE_LIB=${input.sarscapeLib}`,
    ];
    // 行尾必须 CRLF：cmd 的 for/f 解析 LF(\n) 行尾会吞掉行内容（如 SLC_DATA 值被截断），
    // 导致 bat 路径错误（assets/SKILL.md:419-421 铁律，2026-08-18 民勤实测）。
    return lines.join("\r\n") + "\r\n";
}
/** 写 config.env 到实验目录（resultRoot 根下）。 */
export function writeConfigEnv(resultRoot, input) {
    const envPath = join(resultRoot, "config.env");
    mkdirSync(resultRoot, { recursive: true });
    writeFileSync(envPath, buildConfigEnv(input), "utf8");
    return envPath;
}
